@startuml
(*) --> 收到身份变更消息
if  当前身份==身份变更消息中的身份 then
    --> [true] 收到身份变更消息
else
    --> [false] 取消其他消息订阅
    --> 清空共识票池
    --> 缓存新身份
    --> 订阅leader状态消息
    --> 订阅顶层节点状态共识请求消息
    --> 订阅共识投票消息
    --> 订阅共识结果消息
    --> 订阅拓扑变化请求消息
    --> 订阅拓扑更新结果消息

endif
@enduml