@startuml
(*) --> 订阅重选leader请求的投票结果消息
--> 清空投票池
--> 构建重选leader投票请求
--> 向所有验证者发生投票请求
--> 启动1s定时器
--> 等待接收消息
--> 收到投票结果
--> 调用投票结果处理函数
--> 等待接收消息
等待接收消息--> 收到超时消息
--> 关闭定时器
等待接收消息--> 收到退出消息
--> 关闭定时器
--> 取消订阅重选leader请求的投票结果消息
--> 退出
@enduml