@startuml
(*) --> 收到订阅消息
--> 新区块到达消息
--> 新区块到达消息处理函数
--> 收到订阅消息
收到订阅消息--> blockchain插入消息
--> 新区块到达消息处理函数
收到订阅消息-->验证区块请求消息 
--> 验证区块请求消息处理函数
--> 收到订阅消息
收到订阅消息--> 验证区块结果消息
--> 验证区块结果消息处理函数
--> 收到订阅消息
收到订阅消息--> 重选leader开始消息
--> 重选leader开始消息处理函数
--> 收到订阅消息
收到订阅消息--> 重选leader成功消息
--> 重选leader成功消息处理函数
--> 收到订阅消息
收到订阅消息--> 定时器超时消息
--> 定时器超时消息处理函数
--> 收到订阅消息
收到订阅消息--> 退出消息
--> 退出
@enduml