@startuml
(*) --> 收到超时消息
--> 当前状态为等待区块验证状态
--> 获取当前leader
if 当前节点==leader then
    --> [true] 退出
else
    --> [false]把当前状态设为重选leader状态
endif
收到超时消息--> 当前状态为等待区块结果状态
--> 把当前状态设为重选leader状态
--> 向leader身份计算服务发出更换leader结果消息 
--> 重选次数加一
收到超时消息--> 当前状态为重选leader状态
--> 重选次数加一
--> 退出
收到超时消息--> 当前状态为其他状态
--> 退出
@enduml