@startuml
(*) --> 订阅更换主节点请求消息
--> 订阅更换主节点结果消息
--> 接收消息
--> 更换主节点请求消息
--> 更换主节点请求消息处理函数
--> 接收消息
接收消息--> 更换主节点结果消息
--> 更换主节点结果消息处理函数
--> 接收消息
接收消息--> 退出消息
--> 退订更换主节点请求消息
--> 退订更换主节点结果消息
--> 退出
@enduml