@startuml

"矿工" as s1 -> "区块生成服务" as s2 : 挖矿结果
s2 -> "区块验证服务" as s3: 挖矿响应
s2 -> s3 : 区块验证请求
s2 -> "leader身份服务" as s4 : 区块验证请求
s3 -> CA : 挖矿请求
CA -> s1 : 挖矿请求
s3 -> s2 : 区块验证共识成功消息
s2 -> s4 : header生成消息
s3 -> s4 : 区块验证结果
s4 -> "顶层节点状态共识" as s5: leader变更通知
s4 -> "顶层节点状态共识" as s3: leader变更通知
s4 -> "顶层节点状态共识" as s2: leader变更通知
@enduml