@startuml

autonumber
ca -> "leader身份服务" as s1 : 发送角色为验证者的角色变更消息
s1 -> s1 : 启动四个微服务
ca -> "重选leader计算服务" as s2 : 新header生成消息
s2 -> 区块生成服务 : leader变更通知
ca -> "重选leader控制服务" as s3 : 新header生成消息
s3 -> s3 : 设置1.5s定时器等待区块验证请求消息
s3 -> s2 : 定时器超时则发送重选leader完成消息
s2 -> 区块验证服务: 发送leader变更消息，leader为空
区块验证服务 -> s3 : 区块验证请求消息
s3 -> s3 : 设置2s定时器等待区块验证结果消息
s3 -> s2 : 定时器超时则发送重选leader完成消息
s2 -> 区块验证服务: 发送leader变更消息，leader为空
s3 -> s3 : 重选轮次+1，发出启动重选会话消息
s3 -> "重选leader 主节点服务" as s4 : 发出停止主节点会话服务消息
s3 -> "重选leader 从节点服务" as s5 : 发出停止从节点会话服务消息
s3 -> s4 : 当前身份是leader则发出启动主节点会话服务消息
s3-> s5 : 当前身份是leader则发出启动从节点会话服务消息
s4 -> s5 : 向所有验证者广播重选leader 请求投票消息(节点间消息)
s5 -> s4 : 向所有验证者广播重选leader 投票消息(节点间消息)
s5 -> s4 : 向所有验证者广播重选leader 成功消息(节点间消息)
s5 -> s3 : 重选leader 成功消息
s5 -> s5 : 退出消息
s4 -> s3 : 重选leader 成功消息
s4 -> s4 : 退出消息
s3 -> s2 : 重选leader 完成消息
s2 -> 区块生成服务 : leader变更通知

@enduml