@startuml

actor Leader
actor Follower
autonumber
Follower->Leader:   Hello
Leader->Follower:   tx_request
Follower->Leader:   send_tx
Leader->Leader:     2s timeout
Leader->Follower:   tx_request
Follower->Leader:   send_tx
Leader->Leader:     2s timeout

activate Leader
Leader->Leader:     去重
Leader->Leader:     验证交易
Leader->Follower:   send_tx
Leader->Leader:     2s timeout
Leader->Follower:   send_tx
Follower->Leader:   recv_timeout
Leader->Follower:   send_tx
Follower->Leader:   recv_ok
deactivate Leader

activate Follower
Follower->Follower: 验证交易
Follower->Leader:   black_list
deactivate Follower

Leader->Leader:     1s timeout
Leader->Follower:   recv_timeout
Follower->Leader:   send_tx

Leader->Follower:   recv_ok
activate Leader
Leader->Leader:     delete_tx
Leader->Follower:   request_vote
deactivate Leader
Follower->Leader:   vote_result


@enduml