@startuml
[*]--> 发送交易请求
发送交易请求 : 设置超时
发送交易请求 : 触发超时，重新发送交易请求
发送交易请求: 验证交易
发送交易请求: 交易去重
发送交易请求--> 失败 

' 发送交易请求--> 接收交易信息
' 接收交易信息--> 失败 
' 接收交易信息 : 验证交易
' 接收交易信息 : 交易去重

发送交易请求--> 向follower发送交易信息
' 接收交易信息 --> 向follower发送交易信息
向follower发送交易信息: 设置超时
向follower发送交易信息: 触发超时，重新发送交易
向follower发送交易信息--> 失败 

向follower发送交易信息 --> 接收无效的交易
接收无效的交易 : 删除交易块中的无效交易
接收无效的交易 :发起投票请求;
接收无效的交易--> 失败 

' 发起投票请求--> 失败 

' 发起投票请求 --> 接收投票信息
接收无效的交易--> 接收投票信息
接收投票信息 : 根据投票信息进行共识
接收投票信息--> 失败 

接收投票信息 --> 执行成功
@enduml