@startuml
title leader整体流程
start
:获取验证网络中验证者节点列表;
:获取矿工节点信息;
while(follow < 10)
    :leader向follower发送交易请求;
    note right
        实际上应该开10个gorutine进行并发操作
    end note
endwhile
:将交易池中的交易数据进行打包;
while(follow < 10)
    :leader向follower发送打包好的交易列表;
endwhile

while(follow < 10)
    :leader接收follower发来的无效交易列表;
endwhile

while(follow < 10)
    :leader向follower发送投票请求;
endwhile

:leader收集所有follower的投票结果;
:leader对收集的投票结果进行共识;
:leader将共识结果发送给矿工节点;
end
@enduml