@startuml
title 将打包好的交易列表发送给follower
start
:调用发送接口将打包好的交易发送给follower;
:启动定时器;
:接收从follower发来的消息;
while (true)
    if (定时器没有触发) then (true)
    if(签名验证正确)then (yes)
        :删除定时器;
        break
    else(no)
        if (重传计数 >= 1) then (true)
            :返回发送错误;
            end
        else (false)
            :调用发送接口将打包好的交易发送给follower;
            :重设定时器;
            :重传计数加一;
        endif
    endif
    else (false)
        if (重传计数 >= 1) then (true)
            :返回发送错误;
            end
        else (false)
            :调用发送接口将打包好的交易发送给follower;
            :重设定时器;
            :重传计数加一;
        endif
    endif
endwhile
    :接收follower发来的无效交易;
    :在打包的交易列表中删除无效的交易;
end
@enduml