@startuml
title 本地挖矿请求处理流程
(*)-->收到本地挖矿请求
if "请求中的数据是否合法" then
    --> [不合法]退出
else
    [合法] if "当前挖矿状态" then
    -->[正在挖矿中 ] 停止挖矿任务
    --> 根据请求更新header和难度列表
    --> 启动挖矿任务
    else
    --> [没有在挖矿] 启动挖矿任务
    endif
endif
--> 退出
@enduml